const doc = {
  definition: {
    openapi: "3.0.0",
    info: {
      version: "1.0.0",
      title: "Teerna API",
      description: `
     Documentation automatically generated by the <b>swagger.autogen</b>
     module.

      Teerna is a Game Master tool designed to aid during RPG sessions. This
      API allows for a client to interact with the Teerna Server.

      Teerna Client is provided as a Web Application built with React.

      Some endpoints result in WebSocket broadcast to other players. This will
      be highlighted in the endpoints as appropriate.
      `
    },
    consumes: ['application/json'],
    produces: ['application/json']
  },
  apis: ['./API/index.js', './API/**/*!(.test).js']
}
module.exports = doc;
