# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy workflow

on:
  push:
    branches: [ master ]
 
jobs: 
  job_one: 
    runs-on: ubuntu-latest
    steps: 
    - name: "testing teerna server ssh connection"
      uses: appleboy/ssh-action@master
      with: 
        host: teerna-project.com
        username: root
        password: FmyhTt6OFb
        port: 22
        script: |
            cd /home/project/Teerna/teerna-app
            git status
