# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Workflow

on:
  push:
    branches: [master]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: "testing teerna server ssh connection"
        uses: appleboy/ssh-action@master
        with:
          host: teerna-project.com
          username: root
          key: ${{ secrets.TEERNA_SECRET }}
          port: 22
          script: |
            cd /home/project/Teerna ;
            git pull origin master ;
            cd client; yarn install --non-interactive --silent && yarn build  ;
            cd ../server; npm install  --quiet --no-progress ;
            pm2 restart index.js ;
            cd ..
            git status ;

